<template>
</template>

<script>
var words = {
"adjectives": [
  "kaunis",
  "vihreä",
  "elinvoimainen",
  "taisteleva",
  "runsas",
  "kuulas",
  "viileä",
  "kultainen",
  "synkkä",
  "herkkä",
  "rehevä",
  "punainen",
  "musta",
  "sininen",
  "keltainen",
  "oranssi",
  "valkoinen",
  "valkea",
  "arvaamaton",
  "salainen",
  "kirkas",
  "synkkä",
  "kellertävä",
  "kuulas",
  "herkkä",
  "elegantti",
  "multainen",
  "erityinen",
  "ainutlaatuinen",
  "energinen",
  "tuoksuva",
  "kasvava",
  "elävä",
  "voimakas",
  "rehevä",
  "räjähtävä",
  "hiuksenhieno",
  "tummanvihreä",
  "kullattu",
  "lyhyt",
  "pitkä",
  "ikuinen",
  "loppumaton",
  "musta",
  "keväänvihreä",
  "taivaansininen",
  "hämärä",
  "synkkä",
  "musta",
  "tumma",
  "kylmä",
  "viileä",
  "raikas",
  "puhdas",
  "kostea",
  "multaisa",
  "huojuva",
  "karhea",
  "villi",
  "raivoava",
  "usvaisa",
  "elävä",
  "ainutlaatuinen",
  "miehekäs",
  "naisellinen",
  "koskettava",
  "pistelevä",
  "kasvava",
  "kuhiseva",
  "kirkas",
  "ainoa",
  "ajankohtainen",
  "kahiseva",
  "riipaiseva",
  "runollinen",
  "uskalias",
  "ujo",
  "satumainen",
  "aavemainen",
  "autio",
  "yksinäinen",
  "tyhjä",
  "punertava",
  "maukas",
  "kypsyvä",
  "ikivanha",
  "aava",
  "aakea",
  "yksin",
  "hiljainen",
  "koskematon",
  "höyhenenkevyt",
  "seitinohut",
  "kuulas",
  "kirkas",
  "raikas",
  "uljas",
  "rento",
  "nuori",
  "vanha",
  "ikivanha",
  "hengellinen",
  "antoisa",
  "kallisarvoinen",
  "suomalainen",
  "kotimainen",
  "luonnollinen",
  "terveellinen",
  "kaiho",
  "surullinen",
  "uupunut",
  "vilkas",
  "nöyrä"
],
"adjectivesEng": [
  "fresh",
  "windy",
  "clean",
  "green",
  "chilly",
  "red",
  "well",
  "good",
  "cozy",
  "happy",
  "content",
  "cheerful",
  "rough",
  "cold",
  "freezing",
  "alive",
  "lively",
  "calm",
  "dense",
  "thick",
  "ancient",
  "secret",
  "hidden",
  "massive",
  "deep",
  "boreal",
  "unbroken",
  "wild",
  "enchanted",
  "lush",
  "natural",
  "open",
  "tall",
  "magnificent",
  "silent",
  "distant",
  "immense",
  "blissful",
  "buzzing",
  "inspiring",
  "fresh",
  "playing",
  "pure",
  "rainy",
  "fragrant",
  "fertile",
  "growing",
  "sweet",
  "earthly",
  "woodland",
  "forgiving",
  "dense",
  "undisturbed",
  "lonely",
  "mighty",
  "largest",
  "fresh",
  "fir",
  "cool",
  "yellow",
  "thawed",
  "obscured",
  "slender",
  "sharp",
  "sunlit",
  "dusky",
  "vivid",
  "barren",
  "thriving",
  "harsh",
  "unpredictable",
  "young",
  "alluring",
  "elegant",
  "black",
  "blue",
  "clear",
  "remote",
  "cold",
  "fragrant",
  "hazy",
  "light",
  "old",
  "ancient",
  "beautiful",
  "mysterious",
  "silent",
  "amazing",
  "graceful"
],
"verbs": [
  "poimia",
  "poimin",
  "paistaa",
  "kaatua",
  "kasvaa",
  "herään",
  "herää",
  "nousta",
  "nousen",
  "nousee",
  "koittaa",
  "koitan",
  "uskallan",
  "uskalla",
  "menen",
  "menee",
  "annan",
  "antaa",
  "joustaa",
  "elää",
  "elän",
  "nukkuu",
  "nukun",
  "painautuu",
  "painaudun",
  "koskettaa",
  "kuulee",
  "kuulen",
  "unohdan",
  "unohdin",
  "unohtaa",
  "muistaa",
  "muista",
  "muistin",
  "muistan",
  "kasvattaa",
  "juoksee",
  "juoksen",
  "helisee",
  "suree",
  "suren",
  "itken",
  "huojuu",
  "kuultaa",
  "paistaa",
  "menen",
  "menet",
  "menen",
  "laulaa",
  "laulaa",
  "laulan",
  "laula",
  "kuuntele",
  "kuulen",
  "rentoudun",
  "rentoudu",
  "rentoutuu",
  "nautin",
  "nauttii",
  "syön",
  "syö",
  "kerään",
  "kuljen",
  "kulkee",
  "vaellan",
  "vaeltaa",
  "hengähdän",
  "hengähtää",
  "tunnen",
  "tunne",
  "katson",
  "katso",
  "tarkkailen",
  "tarkkailee",
  "kuuntelen",
  "kuuntelee",
  "kuuntele",
  "huudan",
  "huutaa",
  "piiloudun",
  "piiloutuu",
  "katoaa",
  "hämärtyy",
  "kadotan",
  "piilotan",
  "löydän",
  "löytyy",
  "poimin",
  "kurotan",
  "käpertyy",
  "käperryn",
  "istahdan",
  "istahtaa",
  "istun",
  "istuu",
  "hiihtelen",
  "kulkea",
  "soi",
  "soittaa",
  "taivaltaa",
  "lipuu",
  "hidastelen",
  "rauhoitun",
  "hiihdän",
  "kiiruhdan",
  "hiljennyn",
  "leikkii",
  "leikin",
  "palaa",
  "syttyy",
  "loimuaa",
  "hohtaa",
  "kimmeltää",
  "kiiltää",
  "kipinoi",
  "hiljentyy",
  "jäljitän",
  "tuudittaa",
  "havisee",
  "visertää",
  "ulvoo",
  "kaipaan",
  "kohisee",
  "sataa",
  "myrskyää",
  "tuulee"
],
"verbsEng": [
  "running",
  "am",
  "should",
  "will",
  "want",
  "love",
  "sing",
  "live",
  "protect",
  "growing",
  "lend",
  "imagine",
  "stay",
  "listen",
  "collect",
  "pick",
  "dig",
  "feel",
  "see",
  "hear",
  "live",
  "can",
  "will",
  "should",
  "isn't",
  "is",
  "is",
  "is",
  "is",
  "is",
  "is",
  "will",
  "love",
  "cherish",
  "remember",
  "flying",
  "running",
  "wants",
  "love",
  "find",
  "does",
  "doesn't",
  "would",
  "will",
  "wouldn't",
  "couldn't",
  "can",
  "can't",
  "could",
  "yearns",
  "shining"
],
"substantives": [
  "koivu",
  "mänty",
  "metsä",
  "honka",
  "petäjä",
  "auringonlasku",
  "tähdenlento",
  "ukkonen",
  "kangas",
  "sydän",
  "sammal",
  "oksa",
  "käpy",
  "sieni",
  "kaipuu",
  "liekki",
  "nuotio",
  "kuiske",
  "tuli",
  "leirinuotio",
  "teltta",
  "kota",
  "laavu",
  "polku",
  "reitti",
  "kartta",
  "haapa",
  "kelo",
  "tikka",
  "käki",
  "pesä",
  "sulka",
  "höyhen",
  "lehti",
  "ranta",
  "marja",
  "luonto",
  "puutarha",
  "kuolema",
  "kehto",
  "aika",
  "tähtien",
  "uni",
  "unessa",
  "hanki",
  "luonnossa",
  "luontoon",
  "luonnon",
  "metsä",
  "metsät",
  "metsässä",
  "metsän",
  "myrskytuuli",
  "kevätsää",
  "talvimyrsky",
  "tuisku",
  "nuoska",
  "lumikide",
  "horsma",
  "poimulehti",
  "niitty",
  "yö",
  "yöllä",
  "päivä",
  "yön",
  "elämä",
  "elämän",
  "suuruus",
  "usva",
  "lampi",
  "juhannus",
  "kesäyö",
  "sammalmätäs",
  "laulu",
  "syksyllä",
  "keväällä",
  "kesällä",
  "talvella",
  "hanki",
  "lumi",
  "lumihanki",
  "jälki",
  "jäljet",
  "orava",
  "eläin",
  "eläimet",
  "jänis",
  "hirvi",
  "poro",
  "karhu",
  "otso",
  "kallio",
  "kivi",
  "ravinto",
  "henki",
  "hengissä",
  "elossa",
  "kehto",
  "lapsi",
  "poikanen",
  "susi",
  "muurahainen",
  "kanto",
  "eväät",
  "termospullo",
  "neulanen",
  "korpi",
  "metso",
  "teeri",
  "karpalo",
  "puolukka",
  "mustikka",
  "kukka",
  "nuppu",
  "aromi",
  "auringonvalo",
  "sade",
  "todellisuus",
  "usva",
  "maassa",
  "aika",
  "unia",
  "halla",
  "tihku",
  "sumu",
  "kumisaappaat",
  "kyy",
  "lintu",
  "eläin",
  "tiainen",
  "korppi",
  "sammal",
  "koski",
  "pelto",
  "laakso",
  "vaara",
  "pesä",
  "koti",
  "kolo",
  "vuori",
  "muisto",
  "hetki",
  "tuoksu",
  "koivu",
  "mänty",
  "lähde",
  "puro",
  "tunturi",
  "syksy",
  "kevät",
  "kesä",
  "talvi",
  "korpi",
  "muisto",
  "hetki",
  "tuoksu",
  "savi",
  "kangas",
  "aurinko",
  "kuu",
  "tähdet",
  "taivas",
  "pilvet",
  "suo",
  "räme",
  "oja",
  "naava",
  "halla",
  "kuura"
],
"substantivesEng": [
  "bear",
  "wolf",
  "dream",
  "reality",
  "midsummer",
  "moment",
  "feather",
  "heather",
  "nature",
  "natural",
  "lifetime",
  "season",
  "day",
  "wind",
  "breath",
  "call",
  "wild",
  "moor",
  "cliff",
  "granite",
  "night",
  "midnight",
  "evening",
  "mosquito",
  "anthill",
  "pond",
  "sound",
  "thunder",
  "day",
  "pine",
  "pinecone",
  "birch",
  "elk",
  "moose",
  "reindeer",
  "hare",
  "rabbit",
  "squirrel",
  "blueberry",
  "raspberry",
  "warmth",
  "sunlight",
  "summer",
  "brook",
  "water",
  "snowflake",
  "auroras",
  "skiing",
  "moment",
  "memory",
  "branches",
  "trees",
  "forest",
  "forest",
  "forest",
  "forest",
  "scent",
  "fog",
  "smoke",
  "willow",
  "deer",
  "rabbit",
  "track",
  "pawprint",
  "snow",
  "mountain",
  "home",
  "cabin",
  "grass",
  "moss",
  "sunset",
  "river",
  "sunlight",
  "night",
  "stars",
  "moon",
  "rain",
  "snow",
  "flame",
  "campfire",
  "smoke",
  "leaves",
  "berries",
  "forest",
  "stream",
  "sun",
  "moon",
  "night",
  "winter",
  "summer",
  "trees",
  "spring",
  "flowers",
  "nature",
  "nest",
  "fur",
  "swamp",
  "midnight",
  "hunter"
],
"misc": [
  "jos",
  "joskus",
  "kerran",
  "aina",
  "missä",
  "siellä",
  "kenet",
  "miksi",
  "emme",
  "voi",
  "minut",
  "sinut",
  "meidät",
  "teidät",
  "heidät",
  "kenen",
  "ainoa",
  "mennyt",
  "tuleva",
  "ken",
  "vaikka",
  "joka",
  "jokainen",
  "mennyt",
  "kuin",
  "kun",
  "kunnes",
  "asti",
  "väärä",
  "joku",
  "jonkun",
  "jotain",
  "jollei",
  "minne",
  "milloin",
  "silloin",
  "siellä",
  "sinne",
  "siksi",
  "miksi",
  "miksei",
  "on",
  "eilinen",
  "tuskin",
  "alla",
  "yllä",
  "ja",
  "ja",
  "ja",
  "ja",
  "ja",
  "ja",
  "ehkä",
  "ehkä",
  "vielä",
  "tai",
  "kai",
  "ken",
  "tänään",
  "ikuinen",
  "aina",
  "ehkei",
  "ei",
  "ei",
  "en",
  "en",
  "et",
  "et",
  "minä",
  "minä",
  "sinä",
  "sinä",
  "se",
  "sinä",
  "kyllä",
  "ehkä",
  "jopa",
  "kuin"
],
"miscEng": [
  "only",
  "always",
  "today",
  "not",
  "no",
  "to",
  "to",
  "to",
  "to",
  "I",
  "no",
  "perhaps",
  "might",
  "yet",
  "still",
  "while",
  "for",
  "because",
  "you",
  "they",
  "barely",
  "even",
  "though",
  "like",
  "where",
  "there",
  "why",
  "not",
  "cannot",
  "every",
  "each",
  "yesterday",
  "tomorrow",
  "future",
  "over",
  "too",
  "too",
  "too",
  "to",
  "I",
  "I",
  "do",
  "does",
  "she",
  "she",
  "the",
  "the",
  "the",
  "the",
  "the",
  "of",
  "of",
  "of",
  "of",
  "of",
  "of",
  "of",
  "of",
  "of",
  "he",
  "he",
  "it",
  "it",
  "why",
  "when",
  "where",
  "here",
  "there",
  "because",
  "since",
  "nobody",
  "no-one",
  "then",
  "when"
]
};

export default {
  name: 'word',
  data () {
    return {
      word: "init",
      textElement: {},
      controlElement: {},
      elementGroup: {}
    }
  },

  props: ['type', 'canvas', 'lang'],

  computed: {
    isFinnish: function () {
      return this.lang === "FI"
    }
  },

  watch: {
    isFinnish: 'changeLanguage'
  },

  created: function () {
    var self = this;

    this.word = words[this.type.type][Math.floor(Math.random()*words[this.type.type].length)];

    this.textElement = new fabric.IText(this.word, {
      left: self.type.startPos.x,
      top: self.type.startPos.y,
      textBackgroundColor: 'rgb(0,0,0)',
      fill: 'rgb(255,255,255)',
      fontFamily: 'Courier',
      angle: (10-(Math.random()*20))
    });

    var controlElementLabel, removalElementLabel;
    if(self.isFinnish) {
      controlElementLabel = 'Vaihda\nsana';
      removalElementLabel = 'Poista\nsana';
    } else {
      controlElementLabel = 'Randomize\nword';
      removalElementLabel = 'Remove\nword';
    }

    this.controlElement = new fabric.Text(controlElementLabel, {
      fill: '#28b',
      fontSize: 25,
      fontFamily: 'Courier',
      textBackgroundColor: '#FFF',
      hasControls: false,
      lockMovementX: true,
      lockMovementY: true,
      selectable: false,
      hoverCursor: 'pointer',
      visible: false
    });

    this.removalElement = new fabric.Text(removalElementLabel, {
      fill: '#F00',
      fontSize: 25,
      fontFamily: 'Courier',
      textBackgroundColor: '#FFF',
      hasControls: false,
      lockMovementX: true,
      lockMovementY: true,
      selectable: false,
      hoverCursor: 'pointer',
      visible: false
    });

    this.canvas.add(this.textElement);
    this.canvas.add(this.controlElement);
    this.canvas.add(this.removalElement);
    this.moveControlElementsTo(this.textElement);
    this.canvas.renderAll();

    this.canvas.on('object:moving', function(evt) {
      if (evt.target === self.textElement) {
        self.moveControlElementsTo(evt.target);
      }
    });

    this.canvas.on('object:rotating', function(evt) {
      if (evt.target === self.textElement) {
        self.controlElement.setVisible(false);
        self.removalElement.setVisible(false);
      }
    });

    this.canvas.on('mouse:down', function(options) {
      if (options.target === self.controlElement) {
        self.refresh();
      } else if (options.target === self.removalElement) {
        self.textElement.remove();
        self.controlElement.remove();
        self.removalElement.remove();
      } else if (options.target === self.textElement) {
        self.controlElement.setVisible(true);
        self.removalElement.setVisible(true);
      } else {
        self.controlElement.setVisible(false);
        self.removalElement.setVisible(false);
      }
    });

    this.canvas.on('object:selected', function(options) {
      if (options.target === self.textElement) {
        self.controlElement.setVisible(true);
        self.removalElement.setVisible(true);
      }
    });
  },

  methods: {
    refresh: function() {
      var wordclassesFin = ["adjectives", "verbs", "substantives", "misc"];
      var wordclassesEng = ["adjectivesEng", "verbsEng", "substantivesEng", "miscEng"];
      if(this.isFinnish) {
        var wordclasses = wordclassesFin;
      } else {
        var wordclasses = wordclassesEng;
      }

      var wordType = wordclasses[Math.floor(Math.random()*wordclasses.length)];
      this.word = words[wordType][Math.floor(Math.random()*words[wordType].length)];
      this.textElement.setText(this.word);
      this.canvas.renderAll()
    },
    changeLanguage: function() {
      if(this.isFinnish) {
        this.controlElement.setText('Vaihda\nsana');
        this.removalElement.setText('Poista\nsana');
      } else {
        this.controlElement.setText('Randomize\nword');
        this.removalElement.setText('Remove\nword');
      }
      this.canvas.renderAll()
    },
    moveControlElementsTo: function(el) {
      this.controlElement.setLeft(el.getLeft() - 80);
      this.controlElement.setTop(el.getTop() - 40);
      this.controlElement.setCoords();

      this.removalElement.setLeft(el.getLeft() - 80);
      this.removalElement.setTop(el.getTop() + 40);
      this.removalElement.setCoords();

      this.canvas.renderAll()
    }
  }
}



</script>
